### ISSUE TITLE
Right clicking on Quick Launch icons launches the program

### ISSUE THREAD

**Issue by Hayafumi** [WinClassic/SimpleClassicTheme.Taskbar#40]
When right clicking on one of the icons on Quick Launch, instead of showing the context menu, it launches the app

**Comment by Craftplacer** [comment]
Confirmed for myself, will look into it, might just only trigger starting the app on left click while we don't have a proper context menu for quick launch items.

**Comment by Craftplacer** [comment]
Fixed with https://github.com/WinClassic/SimpleClassicTheme.Taskbar/commit/85e69d865c853929cc01ee89780801f9184445c3
